name:                tfl-app
version:             0.1.0.0
github:              "user/haskell-api-db"
license:             BSD3
author:              "Your Name"
maintainer:          "your.email@example.com"
copyright:           "2025 Your Name"

extra-source-files:
- README.md

description:         Haskell project with JSON parsing, HTTP calls, and SQLite

dependencies:
- base >= 4.7 && < 5
- aeson >= 2.0
- http-conduit >= 2.3
- bytestring >= 0.10
- text >= 1.2
- sqlite-simple >= 0.4
- mtl >= 2.2

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

executables:
  tfl-app:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

library:
  source-dirs: src
  haddock: true
  haddock-arguments:
    - --html
    - --hyperlinked-source